### PR TITLE
docs: typo in comment of function 'next' in interface CommunicationOb…

### PR DESCRIPTION
**Pull request by ankitshubham97**
This commit fixes a typo in the comment of function `next` in interface `CommunicationObserver`.

## Checklist

- [x] Rebased/mergeable
- [x] `yarn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Comment by sranka** [comment]
Thank you @ankitshubham97 for your contributions, there are probably more typos like this in the code base :)

**Review by sranka — APPROVED** [review]

**Comment by sranka** [comment]
@ankitshubham97 please mark the checkbox indicating that you signed the [CLA](https://www.influxdata.com/legal/cla/).

**Comment by ankitshubham97** [comment]
@sranka Done signing the CLA checklist. Also, I have already signed the CLA. Thanks!

**Comment by ankitshubham97** [comment]
> Thank you @ankitshubham97 for your contributions, there are probably more typos like this in the code base :) 

Yeah, I am correcting them as I am spotting them.

**Pull request merged**
