### PR TITLE
Query parameters

### PR DESCRIPTION
**Pull request by backbone87**
Relates https://github.com/influxdata/influxdb/issues/16109

## Proposed Changes

- Added query variables as described in https://github.com/influxdata/influxdb/issues/16109

## Checklist

  - [ ] CHANGELOG.md updated
  - [ ] A test has been added if appropriate
  - [ ] `yarn test` completes successfully
  - [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by backbone87** [comment]
from conversation in another draft PR:
> @sranka
> Good job on your side ... still, there might be problems with backward compatibility, once we introduce something that does not seem to be stable enough. There is no documentation and the things that are reverse-engineered might change easily. I am also not sure whether this is working against InfluxDB 1.8, which must be supported as well. We should also plan support for query parameters in all client libraries once it is stable, so they are in sync. I am now not sure whether this is a good step forward, maybe that we will need other stakeholders herein.

**Comment by backbone87** [comment]
> There is no documentation and the things that are reverse-engineered might change easily.

actually there is documentation: https://v2.docs.influxdata.com/v2.0/api/#operation/PostQuery

it currently does not work with 1.8 (see https://github.com/influxdata/influxdb/issues/17794), but this does not line up with the claims made here https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-2-0-api-compatibility-endpoints so i hope this will be made available in an 1.8.x version

> We should also plan support for query parameters in all client libraries once it is stable, so they are in sync.

the only things that would change are "how" parameters are passed via the API, not "what" can be passed. client libraries also should be able to map the target env model (in JS case: string, number, boolean, object, Array etc) to the flux values, so i dont think this will be uniform across different clients.

personally i thought this extern stuff is a little bit daunting, but in the end its super flexible and making it work with some baseline set of javascript values was pretty straightforward.

**Comment by backbone87** [comment]
rebased on current master

**Comment by sranka** [comment]
@backbone87 The present v2 documentation does not explain how to pass query parameters (unlike v1), it required some reverse engineering to make this happen, as you pointed out [here](https://github.com/influxdata/influxdb-client-js/pull/177#discussion_r411271201). It is impossible for me to review the code, which should be better approved by integration tests.

Going on with flux AST in "extern" (assuming that there will be no better choice), should we use the =v= object for variables in the flux query (at least by convention)? Are there some clashes if we don't? Let's wait for somebody savvy (in flux, API, planning)  to step into influxdata/influxdb#16109 to decide what to do.

**Comment by backbone87** [comment]
> It is impossible for me to review the code, which should be better approved by integration tests.

the open api spec of the v2 influx api defines the structure of the extern property and the extern payload could be statically verified with some json schema/open api validator with a running influx instance.

> should we use the =v= object for variables in the flux query (at least by convention)?

its already used as a convention by influx' own UI, but we can make it configurable via options (not per query)

---

> Let's wait for somebody savvy (in flux, API, planning) to step into influxdata/influxdb#16109 to decide what to do.

some feedback would be useful, yes. but even if the decision is made "extern" is "unofficial" (it currently is in the api spec so i would expect it to stay) and a new "params" option is introduced, it doesnt block us from merging this variant now, as long as we can make sure that we can map the passed parameters to the new API property once available. from the perspective of a user of this client lib, i would expect to be able to pass everything that is assignable to:
```ts
type FluxParameterLike = 
  | string
  | number // dynamic int or float
  | boolean
  | null
  | undefined // maps to null, except in dictionaries, where the prop is skipped, same behavior as JSON.stringify
  | Date
  | {[k: string]: FluxParameterLike}
  | FluxParameterLike[]
  | SOME_DURATION_TYPE
  | SOME_UNSIGNED_INT_TYPE
  | SOME_INT_TYPE // since we dont have explicit int type in js/ts
  | SOME_FLOAT_TYPE // since we dont have explicit float type in js/ts
```
for the `SOME_*` types i intergrated the builder pattern, but the symbol of the interface is kept private for now, so we have full control over it and people dont start to implement their custom mappings against the flux AST. also i havent implemented the explicit number subtypes(, yet).

the only unsolvable situation would be, if the decision is made to just use JSON types and require the user to pass non JSON compatible flux types as strings and cast them in the flux script. then the possible types reduce to:
```ts
type FluxParameterLike = 
  | string
  | number
  | boolean
  | null
  | undefined
  | {[k: string]: FluxParameterLike}
  | FluxParameterLike[]
```
that leaves us with `Date | SOME_DURATION_TYPE` (+ the other not implemented flux number types, but i wouldnt implement them for now to keep the API surface small) that might be incompatible, but could be worked around by prefixing the query text with preparation code that casts the string representations of these values into flux types.

**Comment by sranka** [comment]
I am on your side Oliver, I understand the need for parameters, and also the simplicity of your approach in this PR. I only mean that we can stay ready herein for a while because there are issues on the server-side that need to be fixed as well ... and the situation might get more clear soon. We can then proceed quickly herein.

Regarding the testing part of this pull request, I don't think that schema validation of AST would help to keep things stable. I can imagine a simple test that could be run against a live server ( and a mock by default) to prove that parameter implementation works as we expect.

**Comment by sranka** [comment]
https://github.com/influxdata/influxdb-client-go/blob/v0.1.5/internal/ast/ast.go#L20 ... params to extern in (old version) of v2 client

**Comment by backbone87** [comment]
my go fu is not that strong, but from what i understand its pretty much the same except that we dont support flux regexp (was unaware of that, and idk if there are dialect differences from JS regexp to influx/go regexp) & unsigned int

**Comment by sranka** [comment]
yes, + 
- there is a validation of _variable name_ rules
- a few suspicious things 
   - https://github.com/influxdata/influxdb-client-go/blob/v0.1.5/internal/ast/ast.go#L70
   - missing float support (from go's float32, float64)
- the generated AST is a bit different: 
   - there is no top-level `OptionStatement`, there is no =v= prefix 
   - nil values are simply ignored

For the sake of clarity, I am also adding influx v2 UI details about parameter handling:  
- the way of how extern is created: https://github.com/influxdata/influxdb/blob/master/ui/src/variables/utils/buildVarsOption.ts
- supported literal parameters: https://github.com/influxdata/influxdb/blob/master/ui/src/variables/utils/formatVarsOption.test.ts#L25

We also have to decide (from a functional perspective) the way of how to represent query parameters in the query and be consistent in all v2 clients. It is good to wrap them into an object expression, but I would rather use other name than `v` (such as `params`). I think that there is no real convention yet. I also think that there is no need to let the user supply an object expression as a query parameter and simple literals and array should be enough, at least initially, until a case for doing so is clear. 

Regarding regexp, we can add a note that https://github.com/google/re2/wiki/Syntax is supported.
  
  -

**Comment by backbone87** [comment]
> I also think that there is no need to let the user supply an object expression as a query parameter

i actually would really like this, since you can compare objects in flux by value, and i already had instances where it would very much simplify my flux query

**Comment by backbone87** [comment]
> Regarding regexp, we can use js RegExp and add a note that https://github.com/google/re2/wiki/Syntax is supported.

i think we missunderstood: we cant serialize a JS regexp into JSON for reuse in flux, since the JS regexp may have a different feature set/dialect than the ones used in influx (go regexp i guess)

**Comment by sranka** [comment]
Regarding object support: np if you have a good case for doing so
Regarding regexp: the clean way is to have a helper for regexp as it is currently for duration, I mean and we might also accept js RegExp (its toString()) since there might be probably differences in corner cases see https://regex101.com/ ... to be decided

**Comment by sranka** [comment]
@backbone87 I have some news herein. We shouldn't rely upon "extern" to supply query parameters and a change to a cleaner API isn't going to happen soon. From my POV, the support of query parameters (via extern) is not stable enough to introduce this in our client libraries, unless there is no other solution. 

I am thinking about a solution that will sanitize query parameters using a new `query` tagged template. The code might then look like:

```js
const query = flux`from(bucket: "my-bucket")  |> range(start: ${start}, stop: ${stop})`
```

**Comment by sranka** [comment]
#186 provides an alternative solution

**Comment by sranka** [comment]
@backbone87 I think that we can close this PR, if you don't mind. #186 provides a solution with all the technical details hidden underneath

**Pull request closed without merging**
